### ISSUE TITLE
Setup for simple_example

### ISSUE THREAD

**Issue by wlund-pivotal** [spring-projects/spring-xd-samples#28]
I'm trying to run a variation of simple_example that uses the module upload and can't get it to work.  The straight forward example works when I setup the module under XD_INSTALL.  

I have:

#Custom module registry location
#Any custom modules built can be placed into this configured location
#The location must be set to a valid resource URL (file://, classpath:/ etc.,)
xd:
  customModule:
    home: file:///Users/wlund/xd-custom-modules

Its not clear whether just setting up the directory should work but on files with jars when I use module upload it does work.

xd:>module upload --file /Users/wlund/xd-custom-modules/rsasession-stream-ingest/lib/rsasession-stream-1.0.0-SNAPSHOT.jar --name rsasession-stream-ingest --type job
Successfully uploaded module 'job:rsasession-stream-ingest'

However, I get the following on setting up the same example in xd-custom-modules:

module upload --file /Users/wlund/xd-custom-modules/simple-example --name simple_example --type job
Command failed org.springframework.web.client.ResourceAccessException: I/O error on POST request for "http://localhost:9393/modules/job/simple_example":/Users/wlund/xd-custom-modules/simple-example (Is a directory); nested exception is java.io.FileNotFoundException: /Users/wlund/xd-custom-modules/simple-example (Is a directory).

Can't seem to get it to work without being under the XD_INSTALL directory.  Am I doing something wrong?

**Comment by ericbottard** [comment]
`xd.customModule.home` is a location where custom modules can be placed (according to a _module registry_ layout, explained) and/or where uploaded (with the `module upload` command) modules will end up.

You do not need (and as a matter of fact should **not**, as this is what is causing your problem) use that directory as your "build" directory. When using the `module upload` command, the argument to the `--file` option can be any directory.

To make things clearer, keep in mind you could be using two machines for this scenarion: one where you build your module and use the XD shell, and the other one hosting the XD container. The argument to `module upload --file` resides in the former, while the location `xd.customModule.home` is on the latter.

Hope that helps.

PS: Layout of a registry
```
xd.customModule.home/
  source/
    some-module.jar
      ..etc
  processor/
  sink/
  job/
    rsasession-stream-ingest.jar     <-- über-jar after you've uploaded

```

Also, as a further clarification, the argument to `module upload` should be a full module (über jar). That is, if your module project depends on other libs, this should be a jar that has nested jars. It should also contain your module definition inside a `config/` subdir (in the über-jar)

**Comment by wlund-pivotal** [comment]
Got it.  That worked and explained the simple example I had a question about where there was no jar to upload.  Its a simple config file and sample.txt.  

$mkdir -p $XD_HOME/custom-modules/job/simple_example/config
    $ cp simple_example.xml $XD_HOME/modules/job/simple_example/config
    $ cp sample.txt /tmp
Copying my xd-custom-modules/job/simple_example/config works per instruction.  Where I got a little confused was the reference to $XD_HOME as I thought the suggestion was to not install custom modules under the installation directory.  All is well,

Thanks,

Wayne

wlund@pivotal.io
Wayne Lund | Advisory Field Engineer | Mobile:916-296-1893 
Skype: wxlund
http://www.pivotal.io

**Comment by ericbottard** [comment]
Actually, both   options are possible. `xd.customModule.home` used to refer to a place where one would put  her custom modules so they would be picked up, but not mess with the default installation. When we added the `module upload` command, we made it     upload to that   place. Certainly the documentation needs some clarification
