### ISSUE TITLE
Errors building smartgrid-prediction project

### ISSUE THREAD

**Issue by linusviking** [spring-projects/spring-xd-samples#31]
Hi,

I am running into a couple of issues while setting up the smartgrid-prediction repo and would appreciate your assistance. I am using springxd release 1.1.1

Issue 1: I have installed analytic-pmml module in springxd processor via module upload command but the 'predict' stream is not starting and my xd instance throws "Constructor threw exception; nested exception is java.lang.RuntimeException: java.io.FileNotFoundException: class path resource [prediction.pmml] cannot be resolved to URL because it does not exist". I have also noticed that prediction.pmml does not exist in the resource folder of spring-xd-modules/analytics-ml-pmml -- how do I add classpath to prediction.pmml in the prediction folder? 

Issue 2: Cannot start Spring boot app via mvn spring-boot:run --- Error in maven compilation step "Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project smartgrid-frontend: Fatal error compiling: invalid target release: 1.8"

Thanks in advance for your guidance.

**Comment by ericbottard** [comment]
Issue 1 is likely because the pmml file was not correctly embedded in the module itself, as explained in the note at https://github.com/spring-projects/spring-xd-samples/tree/master/smartgrid-prediction#install-the-analytic-pmml-module. Did you use the shell script to build the module? As that note says, that's not something you would typically do anyway. So if you're running locally, you can just change the stream definition to include
```
...
analytic-pmml --inputType=application/x-xd-tuple
              --location=file://<path/to/your/local/prediction.pmml>
              --inputFieldMapping='ts:timestamp,house:house'
...
```

Regarding issue n°2, you'll need to make sure to use JDK8 to compile

**Comment by linusviking** [comment]
Thanks both issues are resolved. I am now able to access the frontend at localhost:8080 but the distribution & load graphs are now showing. Spring boot console shows one error: ERROR 3957 --- [Frontend.main()] f.t.AggregateCounterTimeSeriesRepository : Could not connect to server: http://localhost:9393 Error: SocketTimeoutException: Read timed out 

Configuration the location of aggregate counters via -Dsmartgrid.frontend.aggregateCounterUrl=http://localhost:9393/metrics/aggregate-counters is not helping either.

Thanks

**Comment by ericbottard** [comment]
Can you see the counters via aggregate-counter list in the shell ?

**Comment by linusviking** [comment]
Yes can see the counters in the shell. Also, after restarting the xd node, I was able to see the graphs in the browser. Many thanks.
