### ISSUE TITLE
http post --message is not available in Spring-XD

### ISSUE THREAD

**Issue by austindsouza** [spring-projects/spring-xd-samples#36]
Hi I am running spark-streaming-logger-java-sink example,

I configured Spark cluster and the SpringXD srevers.yml file exactly how you mentioned, i am able upload the module as well as created and deployed new stream 'spark-streaming-java-logger' successfully.

While posting the messages to the stream i got an error that 
xd:>http post --message "foo foo foo"
Option 'message' is not available for this command. Use tab assist or the "help" command to see the legal options

Please Help me to solve this issue.

Thanks

**Comment by ericbottard** [comment]
Hi,

the correct command is `http post --data` (not `--message`). Did you find this in the documentation? If this is the case, we need to fix this.

Also, be wary that this `http post` command is just a convenience in the Spring XD shell. You could have used any http client (for example `curl`) submitting to `http://localhost:9000`

HTH

**Comment by austindsouza** [comment]
Thanks for the reply, 
I found this document in the following link 
https://github.com/spring-projects/spring-xd-samples/blob/master/spark-streaming-logger-java-sink/README.md

**Comment by ericbottard** [comment]
Thanks.

I fixed the README

**Comment by markfisher** [comment]
Thanks @ericbottard. Sorry for the confusion @austindsouza
